[idris2]
url = "https://github.com/spcfox/Idris2"
commit = "fetch-latest:list1-determining"

[custom.all.elab-util]
type = "local"
path = "."
ipkg = "elab-util.ipkg"
test = "elab-util-test.ipkg"

[custom.all.elab-pretty]
type = "local"
path = "."
ipkg = "elab-pretty.ipkg"

[custom.all.elab-util-docs]
type = "local"
path = "."
ipkg = "elab-util-docs.ipkg"

[custom.all.elab-util-test]
type = "local"
path = "."
ipkg = "elab-util-test.ipkg"

[custom.all.prettier]
type   = "git"
url    = "https://github.com/spcfox/prettier"
commit = "latest:list1"
ipkg   = "prettier.ipkg"
